cv_checker/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

# Remove this when you start your proejct
from django.views import debug
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', debug.default_urlconf),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

web/urls.py
from django.urls import path
from . import views
from web import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'web'
urlpatterns = [
    # path('', views.MainView.as_view()),
    path('', views.HomePageView.as_view(), name='home'),
    path('all', views.MainView.as_view(), name='all'),
    path('registration', views.RegistrationView.as_view(), name='registration')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CV</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel=”stylesheet” href="{% static "main.css" %}">
</head>
<body>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

web/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body style="background-image: url({% static 'background.png' %});background-size: cover;  background-repeat: no-repeat;background-attachment: fixed;">
<!-- <p> -->
{% if user.is_authenticated %}

<a href="/accounts/logout"><button type="button" class="btn btn-warning btn-lg" style="position: absolute;top: 50%;left: 70%;">Logout</button></a>
{% else %}
<a href="/accounts/login"><button id="login" type="button" class="btn btn-warning btn-lg" style="position: absolute;top: 50%;left: 70%;">Press here</button></a>
{% endif %}
{% if islocal %}
Some of the samples will require a user login to be created.
<!-- </p> -->
{% endif %}
</body>
{% endblock %}

web/templates/tables.html
{% extends 'base.html' %}
{% block title %}Info{% endblock %}
{% block content %}
    <body>
      {% if user.is_authenticated %}
            <a href="{% url 'logout' %}?next={% url 'web:all' %}"><button type="button" class="btn btn-info" style="float:right;">Logout</button></a>
        {% else %}
            <a href="{% url 'login' %}?next={% url 'web:all' %}"><button type="button" class="btn btn-info">Login</button></a> or
            <a href="{% url 'web:registration' %}?next={% url 'web:all' %}"><button type="button" class="btn btn-info">Registration</button></a>
{% endif %}
    <h3 class="text-center">Applicant information</h3>
    <form method="get" >
      <div class="form-group">
        <select class="form-select" name="vacancy_id">
          <option value="">All vacancies</option>
          {% for vacancy in vacancy_open %}
            <option value="{{ vacancy.id }}">{{ vacancy.name }}</option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-info">Show</button>
      </div>
      
    </form>
    <table class="table"> 
        <tr>
          <th>Name</th>
          <th>Surname</th>
          <th>Vacancy</th>
          <th>Cover letter</th>
          <th>English</th>
          <th>Work experience</th>
          <th>Type of employment</th>
          <th>Importance</th>
          <th>Technical skills</th>
          <th>Required skills</th>
          <th>Email</th>
          <th>File</th>
          <th>Decline</th>
        </tr>
        {% for resume in resumes %}
        <tr>
            <td>{{ resume.candidate.name}}</td>
            <td>{{ resume.candidate.surname}}</td>
            <td>{{ resume.vacancy.name}}</td>
            <td>{{ resume.cover_letter}}</td>
            <td>{% for req in english%}
            {% if req.candidate.name == resume.candidate.name %}{{ req.value }}{%endif%}
            {%endfor%}</td>
            <td>{% for req in work_experience%}
              {% if req.candidate.name == resume.candidate.name %}{{ req.value }}{%endif%}
            {%endfor%}</td>
            <td>{% for req in type_of_employment%}
                {% if req.candidate.name == resume.candidate.name %}{{ req.value }}{%endif%}
            {%endfor%}</td>
            <td>{% for req in importance%}
                  {% if req.candidate.name == resume.candidate.name %}{{ req.value }}{%endif%}
            {%endfor%}</td>
            <td>{% for req in skills%}
              {% if req.candidate.name == resume.candidate.name %}{{ req.value }}{%endif%}
            {%endfor%}</td>
            <td><ul></ul>{% for req in required_skills%}
              {% if req.candidate.name == resume.candidate.name %}
                <li {% if req.exist %} style="color:green;" {% else %} style="color:red;"{% endif %}>{{ req.skill.value }}</li>
              {%endif%}
            {%endfor%}</ul></td>
            <td>{{ resume.candidate.email }}</td>
            <td><a href="media/{{resume.file}}"><button type="button" class="btn btn-info" {% if not resume.extracted_text%} disabled {%endif%}>Open</button></a></td>
            <!-- <td><a href="{{ resume.decline }}"><button type="button" class="btn btn-warning">Open</button></a></td> -->
            <td><a href= "mailto:{{ resume.candidate.email }}?subject=Thanx for your resume&body=Thanx for your resume, but we cant invite you for interview."><button type="button" class="btn btn-warning" {% if not resume.extracted_text%} disabled {%endif%}>Send Email</button></a></td>
        </tr>
        {% endfor %}
      </table>
    </body>
{% endblock %}